apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: tekton-dog-facts
spec:
  steps:
    - name: retrieve-dog-facts
      image: quay.io/ibmgaragecloud/alpine-curl
      resources: {}
      script: |
        mkdir dog-facts
        cd dog-facts
        curl https://dog-facts-api.herokuapp.com/api/v1/resources/dogs?number=2 > dog-facts.json
        cat dog-facts.json